### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ablanco** [jlsalvador/linter-jslint#1]
It's not possible to install the plugin.

    Installing “linter-jslint@9.0.3” failed.

    Unable to download https://www.atom.io/api/packages/linter-jslint/versions/9.0.3/tarball: 404

**Comment by jlsalvador** [comment]
Thanks for open the issue.
I was cleaning the releases from the parent repository.
Can you try again?

**Comment by ablanco** [comment]
Now it seems to work.
