### ISSUE TITLE
Take "global" option into account

### ISSUE THREAD

**Issue by dorian-marchal** [jlsalvador/linter-jslint#2]
With this `.jslintrc` file :

```
{
  "global" : [
    "require"
  ]
}
```

This plugin show an error on this file :

```
var test = require('../test');
```
![capture du 2016-01-05 11 38 44](https://cloud.githubusercontent.com/assets/6225979/12113093/ececb8aa-b3a0-11e5-8562-00fae9df258e.png)

But from the command line, `jslint` doesn't report any error :

![capture du 2016-01-05 11 40 32](https://cloud.githubusercontent.com/assets/6225979/12113147/316fadac-b3a1-11e5-86b3-38225fae5635.png)

Tested on jslint version 0.9.5 (2013-08-26).

**Comment by jlsalvador** [comment]
I think that the correct option for `.jslintrc` is like the next example:

```
{
    "predef": [
        "require"
    ]
}
```

What do you think?

Source: https://github.com/tcarlsen/atom-jslint/blob/master/.jslintrc-example

**Comment by dorian-marchal** [comment]
It works fine with `predef`, thank you :+1:
