### ISSUE TITLE
.jslintrc is not loaded when several projects are opened

### ISSUE THREAD

**Issue by dorian-marchal** [jlsalvador/linter-jslint#3]
When I open two projects in Atom, the `.jslintrc` file of the second project is not loaded.

**Comment by jlsalvador** [comment]
That's true: https://github.com/jlsalvador/linter-jslint/blob/master/lib/config.coffee#L6
I'll fix that later.

**Comment by dorian-marchal** [comment]
Ok, thank you :+1:

**Comment by dorian-marchal** [comment]
That was fast, thanks you :smile:
