### ISSUE TITLE
How does it differ from the original repository?

### ISSUE THREAD

**Issue by adi518** [jlsalvador/linter-jslint#5]
https://github.com/Joezo/atom-jshint

Thanks.

**Comment by jlsalvador** [comment]
Hi @adi518 

The original repository is https://github.com/AtomLinter/linter-jshint . On the other hand, this plugin it's using [JS**L**int](http://www.jslint.com/) as javascript validation backend instead [JS**H**int](http://jshint.com/).

I have not idea about the repository https://github.com/Joezo/atom-jshint that you refers. Maybe, atom-jshint don't use the [Linter](https://atom.io/packages/linter) framework.
